name: Deploy PHP App to EC2

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for EC2 access using SSH_PRIVATE_KEY_PHP
      - name: Set up SSH for EC2 access
        run: |
          mkdir -p ~/.ssh
          # Use the private key stored in the GitHub secret to create the private key file
          echo "$SSH_PRIVATE_KEY_PHP" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Set the correct permissions
          # Ensure the EC2 host is in the list of known hosts to avoid SSH verification issues
          ssh-keyscan -H ${{ secrets.EC2_PUB }} >> ~/.ssh/known_hosts

      # Step 3: Deploy the code to EC2 using rsync
      - name: Deploy to EC2 using rsync
        run: |
          rsync -avz --delete --exclude='.git' ./ ubuntu@${{ secrets.EC2_PUB }}:/home/ubuntu/php

      # Step 4: SSH into EC2 to restart Apache (or Nginx) service
      - name: Restart Apache on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUB }} << 'EOF'
            sudo systemctl restart apache2  # Use 'nginx' if you're using Nginx
          EOF
