name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3  # A more stable version of the SSH agent action
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to Server using rsync
        run: |
          rsync -avz --exclude='.git' ./ ${USER}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.5  # Stable version
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Exit on any error
            # Update and install necessary software
            sudo apt-get update -y
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            
            # Correct directory path and deploy files
            cd /var/www/html

            # If you need to copy files from a directory like /home/ubuntu/your_project
            sudo cp -r /home/ubuntu/your_project/* /var/www/html/

            # Set the correct ownership and permissions for Apache
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/

            echo "Deployment completed successfully!"
