name: SSH into EC2 instance

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  ssh-to-ec2:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

         - name: Set up SSH key
        run: |
          mkdir -p ~/.test
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.test/file
          chmod 600 ~/.test/file  # Secure the private key

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H <EC2_PUBLIC_IP> >> ~/.ssh/known_hosts

      - name: SSH into EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<EC2_PUBLIC_IP> "echo 'Successfully connected to EC2!'"