name: EC2 SSH Login with Password

on:
  push:
    branches:
      - main  # This can be adjusted based on your need
env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.USERNAME }}
  EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  AWS_REGION: 'us-east-1'
  ECR_REPOSITORY: 'yashvi/php'
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  IMAGE_TAG: latest
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
      
      
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com


      - name: build docker image
        run: | 
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: tag docker image for ECR
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Set up SSH client
        run: |
          sudo apt-get install -y openssh-client 
            mkdir -p ~/.test
          echo "$EC2_SSH_KEY" > ~/.test/key.pem
          chmod 400 ~/.test/key.pem

      - name: SSH into EC2 and run Docker container
        run: |
           ssh -i  ~/.test/key.pem -o StrictHostKeyChecking=no "$EC2_USERNAME"@"$EC2_HOST" <<EOF
           echo "connected to ec2"
           rsync -avz --exclude=".git" -e "ssh -i  ~/.test/key.pem -o StrictHostKeyChecking=no" ./ "$EC2_USERNAME"@"$EC2_HOST":/var/www/html/
           sudo chown -R www-data:www-data /var/www/html/
           sudo chmod -R 755 /var/www/html/
             sudo systemctl start apache2
           ls -l /var/www/html/
           aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

           docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
           docker run -d --name my-php-container -p 80:80 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
             docker ps
            ls -l /home/$EC2_USERNAME
           EOF

      - name: Verify Docker container is running on EC2
        run: |
          ssh -i  ~/.test/key.pem -o StrictHostKeyChecking=no "$EC2_USERNAME"@"$EC2_HOST" "docker ps"
