name: EC2 SSH Login with Password

on:
  push:
    branches:
      - main  # This can be adjusted based on your need
env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.USERNAME }}
  EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Login to Instance
        run: |
          mkdir -p ~/.test
          echo "$EC2_SSH_KEY" > ~/.test/key.pem
          chmod 400 ~/.test/key.pem

      - name: Upload Files to EC2 (to /var/www/html)
        run: |
          # Upload index.php or other files to /var/www/html for web apps
           rsync -avz -e "ssh -i ~/.test/key.pem -o StrictHostKeyChecking=no" ./index.php "$EC2_USERNAME"@"$EC2_HOST":/var/www/html/

      - name: verify uploaded files
        run: |         
          ssh -i ~/.test/key.pem -o "StrictHostKeyChecking no" -tt "$EC2_USERNAME"@"$EC2_HOST" "ls -l /var/www/html/index.php"
          pwd
          ls
