name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

env:
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # Private key for SSH
  EC2_HOST_DNS: ${{ secrets.HOST_DNS }}  # EC2 public DNS
  EC2_USER: ${{ secrets.USERNAME }}  # EC2 SSH username

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner (Ubuntu)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH and connect to EC2
      - name: Set up SSH and connect to EC2
        run: |
          # Debug: Check that the necessary environment variables are set
          echo "EC2_HOST_DNS: $EC2_HOST_DNS"
          echo "EC2_USER: $EC2_USER"
          
          # Create .ssh directory and set correct permissions
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa  # Use environment variable for SSH key
          chmod 600 ~/.ssh/id_rsa  # Ensure the private key has the correct permissions
          
          # Add EC2 host to known_hosts to avoid authenticity warnings
          #ssh-keyscan -H $EC2_HOST_DNS >> ~/.ssh/known_hosts
          
          # Test SSH connection to EC2 (to check if everything is working)
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST_DNS "echo 'SSH connection successful!'"
          
          # Run commands on the EC2 instance
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST_DNS << EOF
            # Update and install necessary packages
            sudo apt-get update -y
            echo "Deployment completed successfully!"
            pwd
          EOF
