name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      # Optional: Additional commands for configuring Apache or services on EC2
      - name: Configure Apache and deploy files
        run: |
          # Add SSH key and connect to EC2
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts
          
          # Connect to EC2 and run commands
          ssh -i ~/.ssh/id_rsa ${USER}@${{ secrets.HOST_DNS }} <<EOF
            # Update and install Apache
            sudo apt-get update -y
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            
            # Clean existing files in the default web directory
            sudo rm -rf /var/www/html/*

            # Copy the project files to the Apache web directory
            sudo cp -r /home/ubuntu /var/www/html/

            # Set the correct ownership and permissions for Apache
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/

            echo "Deployment completed successfully!"
          EOF
