name: SSH into EC2 instance

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  ssh-to-ec2:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ED25519
          chmod 700 ~/.ssh/ED25519 # Secure the private key
     
      - name: Add EC2 host to known hosts
        run: |
          sudo ssh-keyscan -H 44.204.195.131 >> ~/.ssh/known_hosts 


      - name: SSH into EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-44-204-195-131.compute-1.amazonaws.com "echo 'Successfully connected to EC2!'"
