name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up SSH for EC2 access
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config

      - name: Install dependencies and PHP on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
            sudo apt-get update
            sudo apt-get install -y apache2 php libapache2-mod-php rsync
            sudo systemctl start apache2
            sudo systemctl enable apache2
          EOF

      - name: Install rsync on EC2
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.HOST_DNS }} "sudo apt-get install -y rsync"

      - name: Sync files to EC2 using rsync
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ ${REMOTE_USER}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }} -v

      - name: Restart Apache on EC2 (optional)
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.HOST_DNS }} "sudo systemctl restart apache2"

      - name: Set correct permissions on PHP files
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/
            sudo systemctl restart apache2
          EOF
