name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use GitHub hosted runner (Ubuntu)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH and deploy to EC2
      - name: Set up SSH and connect to EC2
        run: |
          # Create .ssh directory and set correct permissions
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add EC2 host to known_hosts to avoid authenticity warnings
          ssh-keyscan -H ${{ secrets.EC2_HOST_DNS }} >> ~/.ssh/known_hosts

          # Run commands on the EC2 instance
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST_DNS }} << EOF
            # Update and install necessary packages
            #sudo apt-get update -y
            #sudo apt-get install -y apache2

            # Start Apache and enable it to start on boot
            #sudo systemctl start apache2
            #sudo systemctl enable apache2

            # Clean the default web directory
            #sudo rm -rf /var/www/html/*

            # Copy the repository content to Apache web directory
            #sudo cp -r /home/ubuntu/your_project/* /var/www/html/

            # Set ownership and permissions for Apach

            echo "Deployment completed successfully!"
          EOF
