name: SSH into EC2 instance

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  ssh-to-ec2:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
        