name: EC2 SSH Login with Password

on:
  push:
    branches:
      - main  # This can be adjusted based on your needs
env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.USERNAME }}
  EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH Client
        run: sudo apt-get install -y openssh-client

      - name: test ssh key
        run: |
          mkdir -p ~/.test
          echo "$EC2_SSH_KEY" > ~/.test/key.pem
          chmod 400 ~/.test/key.pem
          ssh -i ~/.test/key.pem "$EC2_USERNAME"@"$EC2_HOST"

      - name: Log into EC2 instance
        run: |
          echo "$EC2_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST 'echo "Successfully logged in"'